version: "3.7"

services:
  fastapi:
    build:
      context: .
      dockerfile: DockerfileWebApi
    environment:
      RABBITMQSERVER: amqp://guest:guest@rabbitmq_server:5672
      #REDISSERVER: redis://redis_server:6379
      C_FORCE_ROOT: "true"
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq_server
  worker:
    build:
      dockerfile: DockerfileCelery
      context: .
    environment:
      #REDISSERVER: redis://redis_server:6379
      RABBITMQSERVER: amqp://guest:guest@rabbitmq_server:5672
      C_FORCE_ROOT: "true"
    depends_on:
      - rabbitmq_server
  redis_server:
    image: redis
    environment: 
      - REDIS_HOST=kredis
      - REDIS_PORT=6379
      - REDIS_CELERY_DB_INDEX=10
      - REDIS_STORE_DB_INDEX=0
  
  rabbitmq_server:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
            - "5672:5672"

  flower:
    image: mher/flower
    command: ["flower", "--broker=amqp://guest:guest@rabbitmq_server:5672", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq_server
#//amqp://guest:guest@rabbitmq_server:5672